### ISSUE TITLE
Supporting multiple secure/insecure caches

### ISSUE THREAD

**Issue by ptink** [foundertherapy/django-redis-secure#8]
In use cases where there are multiple caches (some may be secure, some not) e.g. an insecure "default" cache and two secure caches- "secure1" and "secure2"- there is no way to dynamically specify which secure cache to use for `django-rq` functionality, or a way to turn off the `django-rq` functionality by default which can lead to runtime errors.

The `views.py` and `secure_rq.py` modules both require `default_secure_serializer` to be imported from `settings.py`, and `default_secure_serializer` is derived from the `DJANGO_REDIS_SECURE_CACHE_NAME` setting- meaning only one can be specified and will always be used. Which secure cache do I choose to use and what happens if I want to use `django_rq` functionality with both at some stage?

Disclaimer: I am not actually using the `django-rq` functionality right now and only came across this issue because I want to leave my default cache insecure while securing another one (this lead to a runtime error hence my discovery of the `DJANGO_REDIS_SECURE_CACHE_NAME` setting). I can get around this by setting `DJANGO_REDIS_SECURE_CACHE_NAME` to one of my secure caches even though I won't be using the rq functionality, but it might be cleaner to document what this setting is and provide a way to turn off django_rq support if it's not needed.

Not sure how actively this project is supported but after any input on the issue I'm happy to submit a PR if needed.

**Comment by danaspiegel** [comment]
@ptink Thanks for the report. This is a use case we didn't consider, but certainly one that we would like to support (along with fixing up the inheritance/import structure as well).

This project is definitely maintained, though it only sees periodic updates.

If you are able to contribute a code update to fix the above reported issues, we'd love to accept it! If not, we'll take a look at trying to fix it in the next incremental version.

**Comment by waseem-omar** [comment]
Hi @ptink, thanks for the PR. I reviewed it and added some comments/questions.

**Comment by ptink** [comment]
thanks @waseem-omar I've updated the PR to address those

**Comment by ptink** [comment]
apologies- as this seems to be an edge case and not worth a refactor I'll close this as won't-fix :)
